#spring:
#  grape:
#    ali:
#      iot:
#        config:
#          accessKeyId: LTAI4FhwPLppB9JcBKhFv43J
#          accessKeySecret: vUdOu6CKoStFZxG29t35wiwaeUfN36
#          regionId: SHANGHAI
#          uid: 1940213675463409
#          productKey: a1skKPGCozo
#        connect:
#          type: Http2
#        amqp:
#          consumerGroupId: DEFAULT_GROUP
##          signMethod: hmacsha1
#server:
#  port: 12021