spring:
  grape:
    ali:
      iot:
        config:
          accessKeyId: LTAI4FhwPLppB9JcBKhFv43J
          accessKeySecret: vUdOu6CKoStFZxG29t35wiwaeUfN36
          regionId: SHANGHAI
          uid: 1940213675463409
          productKey: a1skKPGCozo
          message-processor-bean-id:
            a1skKPGCozo: defaultMessageProcessor

        connect:
          type: amqp
          subscribe-switch: on
        amqp:
          consumer-group-message-config:
            - consumer-groupId: DEFAULT_GROUP
              message-processor-beanId: defaultMessageProcessor

#          signMethod: hmacsha1
server:
  port: 12021